### USERS ************************************************
### USERS ************************************************

### Get all users
GET http://localhost:5000/api/users

### Register
POST http://localhost:5000/api/auth/register HTTP/1.1
content-type: application/json

{
  "name": "Vital",
  "email": "jttt@mail.ru",
  "password": "11111111",
  "confirmPassword": "11111111"
}

### Login
POST http://localhost:5000/api/auth/login HTTP/1.1
content-type: application/json

{
  "email": "jt@mail.ru",
  "password": "11111111"
}

### POLLS ************************************************
### POLLS ************************************************

### Get all polls
GET http://localhost:5000/api/polls?page=1&limit=20
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczODkzNTg4OSwiZXhwIjoxNzM5NTQwNjg5fQ.jANuOJjTV_00mm_tdo94IQdiQ9_Irz8ByL_H-0z3WpA

### Get own polls
GET http://localhost:5000/api/polls/own?page=1&limit=20
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczODkzNTg4OSwiZXhwIjoxNzM5NTQwNjg5fQ.jANuOJjTV_00mm_tdo94IQdiQ9_Irz8ByL_H-0z3WpA

### Get poll statistics
GET http://localhost:5000/api/polls/2/statistics
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczODkzNTg4OSwiZXhwIjoxNzM5NTQwNjg5fQ.jANuOJjTV_00mm_tdo94IQdiQ9_Irz8ByL_H-0z3WpA

### Create poll
POST http://localhost:5000/api/polls HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczODkzNTg4OSwiZXhwIjoxNzM5NTQwNjg5fQ.jANuOJjTV_00mm_tdo94IQdiQ9_Irz8ByL_H-0z3WpA

{
  "title": "Super poll2",
  "description": "super description",
  "questions": [
    {
      "text": "How old are you?",
      "answers": [
        {"text": "11-20"},
        {"text": "21-30"},
        {"text": "31-40"}
      ]
    },
    {
      "text": "How are you?",
      "answers": [
        {"text": "fine"},
        {"text": "very well"},
        {"text": "bad"}
      ]
    }
  ]
}

### Close poll
PATCH http://localhost:5000/api/polls/2/close HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczODkzNTg4OSwiZXhwIjoxNzM5NTQwNjg5fQ.jANuOJjTV_00mm_tdo94IQdiQ9_Irz8ByL_H-0z3WpA

### Save user answers
POST http://localhost:5000/api/polls/2/save-answers HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczODkzNTg4OSwiZXhwIjoxNzM5NTQwNjg5fQ.jANuOJjTV_00mm_tdo94IQdiQ9_Irz8ByL_H-0z3WpA

{
  "userAnswers": [
    {"questionId": 1, "answerId": 2},
    {"questionId": 2, "answerId": 4}
  ]
}

### Delete all polls
DELETE http://localhost:5000/api/polls
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczODkzNTg4OSwiZXhwIjoxNzM5NTQwNjg5fQ.jANuOJjTV_00mm_tdo94IQdiQ9_Irz8ByL_H-0z3WpA
