### USERS ************************************************
### USERS ************************************************

### Get all users
GET http://localhost:5000/api/users

### Register
POST http://localhost:5000/api/auth/register HTTP/1.1
content-type: application/json

{
  "name": "Vital",
  "email": "jtt@mail.ru",
  "password": "11111111",
  "confirmPassword": "11111111"
}

### Login
POST http://localhost:5000/api/auth/login HTTP/1.1
content-type: application/json

{
  "email": "jtt@mail.ru",
  "password": ""
}

### POLLS ************************************************
### POLLS ************************************************

### Init project
POST http://localhost:5000/api/projects HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoianRAbWFpbC5ydSIsImlhdCI6MTczODIzNzMyNiwiZXhwIjoxNzM4ODQyMTI2fQ.X9nGBx3ClHF1vyArI45nFU4S4R90NEmbWGD1c_F3U5E

{
  "title": "Super projec2",
  "description": "super description"
}


### Delete project
DELETE http://localhost:5000/api/projects/1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoianRAbWFpbC5ydSIsImlhdCI6MTczODIzNzMyNiwiZXhwIjoxNzM4ODQyMTI2fQ.X9nGBx3ClHF1vyArI45nFU4S4R90NEmbWGD1c_F3U5E
